In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("/content/Ecommerce_Order_Test_Dataset.csv")
df.head()

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Gender,City,Category,Product,Payment_Mode,Quantity,Unit_Price,Discount,Rating
0,ORD0001,01-01-2025,06-01-2025,Customer_058,Male,Mumbai,Clothing,Jacket,upi,5,1470.84,0.05,4.4
1,ORD0002,02-01-2025,05-01-2025,Customer_001,Male,Delhi,Books,Data Science Guide,Debit Card,3,2114.91,0.20,3.0
2,ORD0003,04-01-2025,06-01-2025,Customer_047,male,Mumbai,Electronics,Keyboard,Cash,3,3053.63,0.20,3.3
3,ORD0004,06-01-2025,09-01-2025,Customer_034,Female,Chennai,Clothing,Sneakers,Debit Card,2,1427.69,0.00,3.6
4,ORD0005,08-01-2025,15-01-2025,Customer_032,Female,Coimbatore,Clothing,Jeans,UPI,4,752.61,0.20,3.8

In [6]:
print("number of row",df.shape[0])
print("number of column",df.shape[1])

number of row 101
number of column 13

In [7]:
print(df.columns.tolist())

['Order_ID', 'Order_Date', 'Delivery_Date', 'Customer_Name', 'Gender', 'City', 'Category', 'Product', 'Payment_Mode', 'Quantity', 'Unit_Price', 'Discount', 'Rating']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       101 non-null    object
 1   Order_Date     101 non-null    object
 2   Delivery_Date  101 non-null    object
 3   Customer_Name  100 non-null    object
 4   Gender         101 non-null    object
 5   City           100 non-null    object
 6   Category       101 non-null    object
 7   Product        101 non-null    object
 8   Payment_Mode   100 non-null    object
 9   Quantity       101 non-null    int64
 10  Unit_Price     100 non-null    float64
 11  Discount       101 non-null    float64
 12  Rating         100 non-null    float64
dtypes: float64(3), int64(1), object(9)
memory usage: 10.4+ KB

In [9]:
df.describe()

         Quantity   Unit_Price    Discount      Rating
count  101.000000   100.000000  101.000000  100.000000
mean     3.168317  2579.265200    0.092079    3.738000
std      1.456498  1375.131202    0.070969    0.687813
min      1.000000   166.990000    0.000000    2.600000
25%      2.000000  1441.565000    0.050000    3.100000
50%      3.000000  2691.975000    0.100000    3.750000
75%      4.000000  3783.245000    0.150000    4.400000
max      5.000000  4927.900000    0.200000    5.000000

In [10]:
print(df.isnull().sum())

Order_ID         0
Order_Date       0
Delivery_Date    0
Customer_Name    1
Gender           0
City             1
Category         0
Product          0
Payment_Mode     1
Quantity         0
Unit_Price       1
Discount         0
Rating           1
dtype: int64

In [11]:
df['City'] = df['City'].fillna('Unknown')
df['Customer_Name'] = df['Customer_Name'].fillna('Unknown')
print()

In [12]:
mean_rating = df['Rating'].mean()

df['Rating'] = df['Rating'].fillna(mean_rating)

In [13]:
df['Payment_Mode'] = df['Payment_Mode'].fillna('Unknown')

In [14]:
print(df.isnull().sum())

Order_ID         0
Order_Date       0
Delivery_Date    0
Customer_Name    0
Gender           0
City             0
Category         0
Product          0
Payment_Mode     0
Quantity         0
Unit_Price       1
Discount         0
Rating           0
dtype: int64

In [15]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 1

In [16]:
df = df.drop_duplicates()

print("Duplicate rows removed.")

Duplicate rows removed.

In [17]:
print("New shape of DataFrame:", df.shape)

New shape of DataFrame: (100, 13)

In [21]:
df['Gender'] = df['Gender'].astype(str).str.strip().str.title()
df['City'] = df['City'].astype(str).str.strip().str.title()
df['Payment_Mode'] = df['Payment_Mode'].astype(str).str.strip().str.title()

In [20]:
print(df['Gender'].unique())
print(df['City'].unique())
print(df['Payment_Mode'].unique())

['Male' 'Female']
['Mumbai' 'Delhi' 'Chennai' 'Coimbatore' 'Madurai' 'Unknown' 'Pune'
 'Hyderabad' 'Bengaluru']
['Upi' 'Debit Card' 'Cash' 'Credit Card' 'Unknown']

In [22]:
df['Total_Price'] = df['Quantity'] * df['Unit_Price']
df['Discount_Amount'] = df['Total_Price'] * df['Discount']
df['Final_Amount'] = df['Total_Price'] - df['Discount_Amount']

In [23]:
display(df[
    ['Order_ID',
     'Product',
     'Quantity',
     'Total_Price',
     'Discount_Amount',
     'Final_Amount']
])

,Order_ID,Product,Quantity,Total_Price,Discount_Amount,Final_Amount
0,ORD0001,Jacket,5,7354.20,367.710,6986.490
1,ORD0002,Data Science Guide,3,6344.73,1268.946,5075.784
2,ORD0003,Keyboard,3,9160.89,1832.178,7328.712
3,ORD0004,Sneakers,2,2855.38,0.000,2855.380
4,ORD0005,Jeans,4,3010.44,602.088,2408.352
...,...,...,...,...,...,...
95,ORD0096,Table Lamp,5,24341.20,1217.060,23124.140
96,ORD0097,Table Lamp,1,3049.48,304.948,2744.532
97,ORD0098,Exam Guide,4,4787.44,239.372,4548.068
98,ORD0099,Water Bottle,3,12380.31,1238.031,11142.279
99,ORD0100,Headphones,1,1790.90,358.180,1432.720

In [24]:
total_quantity = df['Quantity'].sum()
average_unit_price = df['Unit_Price'].mean()
maximum_unit_price = df['Unit_Price'].max()
minimum_unit_price = df['Unit_Price'].min()
average_rating = df['Rating'].mean()

print("Total Quantity Ordered:", total_quantity)
print("Average Unit Price:", average_unit_price)
print("Maximum Unit Price:", maximum_unit_price)
print("Minimum Unit Price:", minimum_unit_price)
print("Average Rating:", average_rating)

Total Quantity Ordered: 315
Average Unit Price: 2600.2126262626257
Maximum Unit Price: 4927.9
Minimum Unit Price: 166.99
Average Rating: 3.74638

In [26]:
display(df[df['Quantity'] > 3])

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Gender,City,Category,Product,Payment_Mode,Quantity,Unit_Price,Discount,Rating,Total_Price,Discount_Amount,Final_Amount
0,ORD0001,01-01-2025,06-01-2025,Customer_058,Male,Mumbai,Clothing,Jacket,Upi,5,1470.84,0.05,4.400,7354.20,367.7100,6986.4900
4,ORD0005,08-01-2025,15-01-2025,Customer_032,Female,Coimbatore,Clothing,Jeans,Upi,4,752.61,0.20,3.800,3010.44,602.0880,2408.3520
8,ORD0009,15-01-2025,17-01-2025,Customer_040,Male,Pune,Clothing,Jeans,Upi,4,2947.70,0.05,3.200,11790.80,589.5400,11201.2600
10,ORD0011,19-01-2025,21-01-2025,Customer_053,Male,Mumbai,Clothing,Sneakers,Debit Card,5,505.47,0.05,2.900,2527.35,126.3675,2400.9825
11,ORD0012,21-01-2025,27-01-2025,Customer_001,Female,Mumbai,Clothing,Jacket,Cash,5,4395.64,0.20,3.700,21978.20,4395.6400,17582.5600
18,ORD0019,02-02-2025,07-02-2025,Customer_003,Male,Delhi,Books,Exam Guide,Cash,5,1946.02,0.20,3.300,9730.10,1946.0200,7784.0800
19,ORD0020,04-02-2025,06-02-2025,Customer_012,Female,Mumbai,Clothing,T-Shirt,Upi,5,3772.93,0.00,3.738,18864.65,0.0000,18864.6500
20,ORD0021,06-02-2025,11-02-2025,Customer_026,Male,Hyderabad,Home,Cushion,Cash,5,2025.65,0.05,3.100,10128.25,506.4125,9621.8375
22,ORD0023,10-02-2025,15-02-2025,Customer_051,Female,Pune,Home,Table Lamp,Upi,5,2888.50,0.00,4.400,14442.50,0.0000,14442.5000
24,ORD0025,13-02-2025,14-02-2025,Customer_022,Female,Bengaluru,Books,Python Basics,Debit Card,4,280.43,0.10,3.700,1121.72,112.1720,1009.5480
27,ORD0028,19-02-2025,20-02-2025,Customer_014,Male,Pune,Home,Water Bottle,Credit Card,5,469.26,0.05,4.800,2346.30,117.3150,2228.9850
28,ORD0029,20-02-2025,24-02-2025,Customer_028,Male,Chennai,Books,Exam Guide,Credit Card,4,3489.40,0.15,4.600,13957.60,2093.6400,11863.9600
29,ORD0030,22-02-2025,24-02-2025,Customer_005,Female,Madurai,Books,Exam Guide,Debit Card,4,2718.30,0.05,4.900,10873.20,543.6600,10329.5400
30,ORD0031,24-02-2025,01-03-2025,Customer_047,Female,Pune,Electronics,USB Cable,Credit Card,4,3774.56,0.20,2.800,15098.24,3019.6480,12078.5920
32,ORD0033,28-02-2025,03-03-2025,Customer_030,Male,Coimbatore,Books,Python Basics,Debit Card,5,2967.23,0.10,4.800,14836.15,1483.6150,13352.5350
33,ORD0034,02-03-2025,03-03-2025,Customer_046,Female,Coimbatore,Home,Water Bottle,Credit Card,4,3657.99,0.10,3.000,14631.96,1463.1960,13168.7640
39,ORD0040,12-03-2025,19-03-2025,Customer_026,Female,Delhi,Clothing,T-Shirt,Debit Card,5,1446.19,0.05,4.500,7230.95,361.5475,6869.4025
40,ORD0041,14-03-2025,20-03-2025,Customer_048,Female,Bengaluru,Clothing,Sneakers,Upi,5,1115.42,0.10,3.000,5577.10,557.7100,5019.3900
42,ORD0043,18-03-2025,22-03-2025,Customer_039,Female,Coimbatore,Home,Cushion,Credit Card,4,3809.30,0.00,2.900,15237.20,0.0000,15237.2000
44,ORD0045,22-03-2025,29-03-2025,Customer_033,Male,Mumbai,Books,Exam Guide,Credit Card,4,1416.50,0.15,4.200,5666.00,849.9000,4816.1000
45,ORD0046,23-03-2025,28-03-2025,Customer_030,Female,Pune,Books,Novel,Upi,4,208.71,0.05,3.800,834.84,41.7420,793.0980
46,ORD0047,25-03-2025,01-04-2025,Customer_037,Female,Chennai,Books,Novel,Upi,5,2541.01,0.00,3.400,12705.05,0.0000,12705.0500
50,ORD0051,01-04-2025,07-04-2025,Customer_054,Female,Pune,Clothing,Jacket,Cash,5,4100.29,0.00,3.600,20501.45,0.0000,20501.4500
51,ORD0052,03-04-2025,04-04-2025,Customer_005,Female,Chennai,Home,Storage Box,Upi,4,4843.07,0.00,3.400,19372.28,0.0000,19372.2800
53,ORD0054,07-04-2025,13-04-2025,Customer_034,Male,Madurai,Books,Novel,Upi,4,3979.91,0.15,3.300,15919.64,2387.9460,13531.6940
57,ORD0058,14-04-2025,19-04-2025,Customer_058,Male,Pune,Electronics,Keyboard,Credit Card,5,3944.87,0.10,4.700,19724.35,1972.4350,17751.9150
59,ORD0060,18-04-2025,21-04-2025,Customer_058,Female,Hyderabad,Electronics,USB Cable,Debit Card,4,4044.72,0.20,3.900,16178.88,3235.7760,12943.1040
60,ORD0061,20-04-2025,21-04-2025,Customer_032,Male,Chennai,Clothing,Jacket,Upi,5,4525.44,0.05,4.800,22627.20,1131.3600,21495.8400
61,ORD0062,21-04-2025,25-04-2025,Customer_001,Female,Pune,Clothing,T-Shirt,Credit Card,5,3124.59,0.15,4.100,15622.95,2343.4425,13279.5075
62,ORD0063,23-04-2025,27-04-2025,Customer_056,Male,Madurai,Electronics,USB Cable,Upi,5,4904.27,0.05,2.800,24521.35,1226.0675,23295.2825
63,ORD0064,25-04-2025,30-04-2025,Customer_005,Male,Chennai,Electronics,USB Cable,Credit Card,5,3079.63,0.00,4.800,15398.15,0.0000,15398.1500
64,ORD0065,27-04-2025,28-04-2025,Customer_045,Female,Hyderabad,Clothing,Jeans,Credit Card,5,3219.56,0.15,4.100,16097.80,2414.6700,13683.1300
66,ORD0067,01-05-2025,05-05-2025,Customer_016,Male,Coimbatore,Books,Exam Guide,Cash,4,545.91,0.05,2.800,2183.64,109.1820,2074.4580
67,ORD0068,02-05-2025,03-05-2025,Customer_024,Male,Delhi,Electronics,Headphones,Credit Card,5,3659.35,0.00,4.500,18296.75,0.0000,18296.7500
68,ORD0069,04-05-2025,11-05-2025,Customer_016,Male,Mumbai,Books,Novel,Debit Card,4,2782.49,0.20,4.100,11129.96,2225.9920,8903.9680
71,ORD0072,10-05-2025,17-05-2025,Customer_049,Female,Delhi,Home,Water Bottle,Upi,4,1560.00,0.05,4.500,6240.00,312.0000,5928.0000
77,ORD0078,21-05-2025,26-05-2025,Customer_012,Female,Pune,Books,Novel,Cash,5,3867.70,0.00,3.900,19338.50,0.0000,19338.5000
81,ORD0082,28-05-2025,01-06-2025,Customer_033,Female,Coimbatore,Books,Novel,Cash,4,1802.33,0.10,4.600,7209.32,720.9320,6488.3880
83,ORD0084,31-05-2025,05-06-2025,Customer_051,Male,Mumbai,Books,Novel,Credit Card,4,2940.28,0.10,4.600,11761.12,1176.1120,10585.0080
84,ORD0085,02-06-2025,06-06-2025,Customer_043,Male,Bengaluru,Clothing,T-Shirt,Cash,4,1773.66,0.10,2.800,7094.64,709.4640,6385.1760
85,ORD0086,04-06-2025,09-06-2025,Customer_037,Male,Hyderabad,Clothing,T-Shirt,Credit Card,5,2732.59,0.20,3.500,13662.95,2732.5900,10930.3600
87,ORD0088,08-06-2025,09-06-2025,Customer_003,Male,Madurai,Electronics,Headphones,Upi,4,2965.35,0.05,2.900,11861.40,593.0700,11268.3300
88,ORD0089,10-06-2025,17-06-2025,Customer_001,Male,Chennai,Books,Novel,Debit Card,4,2061.47,0.15,3.100,8245.88,1236.8820,7008.9980
91,ORD0092,15-06-2025,17-06-2025,Customer_010,Male,Hyderabad,Books,Novel,Credit Card,4,3512.86,0.15,4.100,14051.44,2107.7160,11943.7240
93,ORD0094,19-06-2025,26-06-2025,Customer_044,Female,Bengaluru,Home,Storage Box,Credit Card,4,4384.16,0.10,3.900,17536.64,1753.6640,15782.9760
94,ORD0095,20-06-2025,26-06-2025,Customer_029,Female,Bengaluru,Home,Storage Box,Upi,4,2624.66,0.00,3.100,10498.64,0.0000,10498.6400
95,ORD0096,22-06-2025,29-06-2025,Customer_013,Male,Coimbatore,Home,Table Lamp,Upi,5,4868.24,0.05,3.400,24341.20,1217.0600,23124.1400
97,ORD0098,26-06-2025,01-07-2025,Customer_031,Male,Mumbai,Books,Exam Guide,Upi,4,1196.86,0.05,4.800,4787.44,239.3720,4548.0680

In [27]:
display(df[df['Rating'] >= 4.5])

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Gender,City,Category,Product,Payment_Mode,Quantity,Unit_Price,Discount,Rating,Total_Price,Discount_Amount,Final_Amount
17,ORD0018,31-01-2025,02-02-2025,Customer_055,Female,Madurai,Books,Data Science Guide,Debit Card,2,4927.90,0.10,5.0,9855.80,985.5800,8870.2200
27,ORD0028,19-02-2025,20-02-2025,Customer_014,Male,Pune,Home,Water Bottle,Credit Card,5,469.26,0.05,4.8,2346.30,117.3150,2228.9850
28,ORD0029,20-02-2025,24-02-2025,Customer_028,Male,Chennai,Books,Exam Guide,Credit Card,4,3489.40,0.15,4.6,13957.60,2093.6400,11863.9600
29,ORD0030,22-02-2025,24-02-2025,Customer_005,Female,Madurai,Books,Exam Guide,Debit Card,4,2718.30,0.05,4.9,10873.20,543.6600,10329.5400
32,ORD0033,28-02-2025,03-03-2025,Customer_030,Male,Coimbatore,Books,Python Basics,Debit Card,5,2967.23,0.10,4.8,14836.15,1483.6150,13352.5350
37,ORD0038,09-03-2025,10-03-2025,Customer_016,Male,Pune,Electronics,Wireless Mouse,Upi,3,1104.72,0.20,4.6,3314.16,662.8320,2651.3280
39,ORD0040,12-03-2025,19-03-2025,Customer_026,Female,Delhi,Clothing,T-Shirt,Debit Card,5,1446.19,0.05,4.5,7230.95,361.5475,6869.4025
43,ORD0044,20-03-2025,21-03-2025,Customer_036,Female,Chennai,Books,Exam Guide,Debit Card,2,329.79,0.20,4.5,659.58,131.9160,527.6640
47,ORD0048,27-03-2025,28-03-2025,Customer_023,Male,Chennai,Clothing,Jacket,Cash,1,2433.43,0.00,4.7,2433.43,0.0000,2433.4300
49,ORD0050,31-03-2025,01-04-2025,Customer_010,Male,Hyderabad,Home,Cushion,Upi,3,1608.11,0.15,4.5,4824.33,723.6495,4100.6805
57,ORD0058,14-04-2025,19-04-2025,Customer_058,Male,Pune,Electronics,Keyboard,Credit Card,5,3944.87,0.10,4.7,19724.35,1972.4350,17751.9150
60,ORD0061,20-04-2025,21-04-2025,Customer_032,Male,Chennai,Clothing,Jacket,Upi,5,4525.44,0.05,4.8,22627.20,1131.3600,21495.8400
63,ORD0064,25-04-2025,30-04-2025,Customer_005,Male,Chennai,Electronics,USB Cable,Credit Card,5,3079.63,0.00,4.8,15398.15,0.0000,15398.1500
67,ORD0068,02-05-2025,03-05-2025,Customer_024,Male,Delhi,Electronics,Headphones,Credit Card,5,3659.35,0.00,4.5,18296.75,0.0000,18296.7500
70,ORD0071,08-05-2025,14-05-2025,Customer_002,Female,Pune,Home,Cushion,Upi,3,4561.31,0.05,4.7,13683.93,684.1965,12999.7335
71,ORD0072,10-05-2025,17-05-2025,Customer_049,Female,Delhi,Home,Water Bottle,Upi,4,1560.00,0.05,4.5,6240.00,312.0000,5928.0000
79,ORD0080,24-05-2025,28-05-2025,Customer_035,Female,Bengaluru,Books,Novel,Cash,1,324.72,0.20,4.7,324.72,64.9440,259.7760
81,ORD0082,28-05-2025,01-06-2025,Customer_033,Female,Coimbatore,Books,Novel,Cash,4,1802.33,0.10,4.6,7209.32,720.9320,6488.3880
83,ORD0084,31-05-2025,05-06-2025,Customer_051,Male,Mumbai,Books,Novel,Credit Card,4,2940.28,0.10,4.6,11761.12,1176.1120,10585.0080
86,ORD0087,06-06-2025,13-06-2025,Customer_012,Female,Chennai,Home,Table Lamp,Debit Card,2,2354.58,0.15,4.5,4709.16,706.3740,4002.7860
97,ORD0098,26-06-2025,01-07-2025,Customer_031,Male,Mumbai,Books,Exam Guide,Upi,4,1196.86,0.05,4.8,4787.44,239.3720,4548.0680

In [28]:
display(df[df['Final_Amount'] > 5000])

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Gender,City,Category,Product,Payment_Mode,Quantity,Unit_Price,Discount,Rating,Total_Price,Discount_Amount,Final_Amount
0,ORD0001,01-01-2025,06-01-2025,Customer_058,Male,Mumbai,Clothing,Jacket,Upi,5,1470.84,0.05,4.400,7354.20,367.7100,6986.4900
1,ORD0002,02-01-2025,05-01-2025,Customer_001,Male,Delhi,Books,Data Science Guide,Debit Card,3,2114.91,0.20,3.000,6344.73,1268.9460,5075.7840
2,ORD0003,04-01-2025,06-01-2025,Customer_047,Male,Mumbai,Electronics,Keyboard,Cash,3,3053.63,0.20,3.300,9160.89,1832.1780,7328.7120
6,ORD0007,11-01-2025,13-01-2025,Customer_048,Female,Delhi,Electronics,Keyboard,Cash,2,4708.61,0.15,2.800,9417.22,1412.5830,8004.6370
8,ORD0009,15-01-2025,17-01-2025,Customer_040,Male,Pune,Clothing,Jeans,Upi,4,2947.70,0.05,3.200,11790.80,589.5400,11201.2600
11,ORD0012,21-01-2025,27-01-2025,Customer_001,Female,Mumbai,Clothing,Jacket,Cash,5,4395.64,0.20,3.700,21978.20,4395.6400,17582.5600
12,ORD0013,22-01-2025,24-01-2025,Customer_016,Female,Madurai,Clothing,Sneakers,Upi,2,2802.78,0.10,3.800,5605.56,560.5560,5045.0040
15,ORD0016,28-01-2025,04-02-2025,Customer_022,Male,Madurai,Electronics,USB Cable,Upi,3,3910.25,0.00,2.800,11730.75,0.0000,11730.7500
17,ORD0018,31-01-2025,02-02-2025,Customer_055,Female,Madurai,Books,Data Science Guide,Debit Card,2,4927.90,0.10,5.000,9855.80,985.5800,8870.2200
18,ORD0019,02-02-2025,07-02-2025,Customer_003,Male,Delhi,Books,Exam Guide,Cash,5,1946.02,0.20,3.300,9730.10,1946.0200,7784.0800
19,ORD0020,04-02-2025,06-02-2025,Customer_012,Female,Mumbai,Clothing,T-Shirt,Upi,5,3772.93,0.00,3.738,18864.65,0.0000,18864.6500
20,ORD0021,06-02-2025,11-02-2025,Customer_026,Male,Hyderabad,Home,Cushion,Cash,5,2025.65,0.05,3.100,10128.25,506.4125,9621.8375
21,ORD0022,08-02-2025,11-02-2025,Customer_016,Female,Hyderabad,Electronics,Wireless Mouse,Upi,3,4162.90,0.15,4.200,12488.70,1873.3050,10615.3950
22,ORD0023,10-02-2025,15-02-2025,Customer_051,Female,Pune,Home,Table Lamp,Upi,5,2888.50,0.00,4.400,14442.50,0.0000,14442.5000
28,ORD0029,20-02-2025,24-02-2025,Customer_028,Male,Chennai,Books,Exam Guide,Credit Card,4,3489.40,0.15,4.600,13957.60,2093.6400,11863.9600
29,ORD0030,22-02-2025,24-02-2025,Customer_005,Female,Madurai,Books,Exam Guide,Debit Card,4,2718.30,0.05,4.900,10873.20,543.6600,10329.5400
30,ORD0031,24-02-2025,01-03-2025,Customer_047,Female,Pune,Electronics,USB Cable,Credit Card,4,3774.56,0.20,2.800,15098.24,3019.6480,12078.5920
31,ORD0032,26-02-2025,27-02-2025,Customer_049,Male,Coimbatore,Electronics,Wireless Mouse,Credit Card,3,4574.51,0.05,4.300,13723.53,686.1765,13037.3535
32,ORD0033,28-02-2025,03-03-2025,Customer_030,Male,Coimbatore,Books,Python Basics,Debit Card,5,2967.23,0.10,4.800,14836.15,1483.6150,13352.5350
33,ORD0034,02-03-2025,03-03-2025,Customer_046,Female,Coimbatore,Home,Water Bottle,Credit Card,4,3657.99,0.10,3.000,14631.96,1463.1960,13168.7640
34,ORD0035,03-03-2025,06-03-2025,Customer_052,Male,Coimbatore,Home,Storage Box,Unknown,3,3809.70,0.10,2.700,11429.10,1142.9100,10286.1900
39,ORD0040,12-03-2025,19-03-2025,Customer_026,Female,Delhi,Clothing,T-Shirt,Debit Card,5,1446.19,0.05,4.500,7230.95,361.5475,6869.4025
40,ORD0041,14-03-2025,20-03-2025,Customer_048,Female,Bengaluru,Clothing,Sneakers,Upi,5,1115.42,0.10,3.000,5577.10,557.7100,5019.3900
41,ORD0042,16-03-2025,21-03-2025,Customer_021,Male,Mumbai,Clothing,T-Shirt,Credit Card,2,4403.28,0.10,2.900,8806.56,880.6560,7925.9040
42,ORD0043,18-03-2025,22-03-2025,Customer_039,Female,Coimbatore,Home,Cushion,Credit Card,4,3809.30,0.00,2.900,15237.20,0.0000,15237.2000
46,ORD0047,25-03-2025,01-04-2025,Customer_037,Female,Chennai,Books,Novel,Upi,5,2541.01,0.00,3.400,12705.05,0.0000,12705.0500
50,ORD0051,01-04-2025,07-04-2025,Customer_054,Female,Pune,Clothing,Jacket,Cash,5,4100.29,0.00,3.600,20501.45,0.0000,20501.4500
51,ORD0052,03-04-2025,04-04-2025,Customer_005,Female,Chennai,Home,Storage Box,Upi,4,4843.07,0.00,3.400,19372.28,0.0000,19372.2800
53,ORD0054,07-04-2025,13-04-2025,Customer_034,Male,Madurai,Books,Novel,Upi,4,3979.91,0.15,3.300,15919.64,2387.9460,13531.6940
57,ORD0058,14-04-2025,19-04-2025,Customer_058,Male,Pune,Electronics,Keyboard,Credit Card,5,3944.87,0.10,4.700,19724.35,1972.4350,17751.9150
58,ORD0059,16-04-2025,19-04-2025,Customer_019,Male,Delhi,Clothing,T-Shirt,Credit Card,2,3232.87,0.00,3.500,6465.74,0.0000,6465.7400
59,ORD0060,18-04-2025,21-04-2025,Customer_058,Female,Hyderabad,Electronics,USB Cable,Debit Card,4,4044.72,0.20,3.900,16178.88,3235.7760,12943.1040
60,ORD0061,20-04-2025,21-04-2025,Customer_032,Male,Chennai,Clothing,Jacket,Upi,5,4525.44,0.05,4.800,22627.20,1131.3600,21495.8400
61,ORD0062,21-04-2025,25-04-2025,Customer_001,Female,Pune,Clothing,T-Shirt,Credit Card,5,3124.59,0.15,4.100,15622.95,2343.4425,13279.5075
62,ORD0063,23-04-2025,27-04-2025,Customer_056,Male,Madurai,Electronics,USB Cable,Upi,5,4904.27,0.05,2.800,24521.35,1226.0675,23295.2825
63,ORD0064,25-04-2025,30-04-2025,Customer_005,Male,Chennai,Electronics,USB Cable,Credit Card,5,3079.63,0.00,4.800,15398.15,0.0000,15398.1500
64,ORD0065,27-04-2025,28-04-2025,Customer_045,Female,Hyderabad,Clothing,Jeans,Credit Card,5,3219.56,0.15,4.100,16097.80,2414.6700,13683.1300
65,ORD0066,29-04-2025,02-05-2025,Customer_004,Female,Bengaluru,Home,Water Bottle,Upi,3,2818.60,0.10,3.300,8455.80,845.5800,7610.2200
67,ORD0068,02-05-2025,03-05-2025,Customer_024,Male,Delhi,Electronics,Headphones,Credit Card,5,3659.35,0.00,4.500,18296.75,0.0000,18296.7500
68,ORD0069,04-05-2025,11-05-2025,Customer_016,Male,Mumbai,Books,Novel,Debit Card,4,2782.49,0.20,4.100,11129.96,2225.9920,8903.9680
69,ORD0070,06-05-2025,10-05-2025,Customer_055,Male,Hyderabad,Home,Table Lamp,Cash,3,2309.46,0.15,3.800,6928.38,1039.2570,5889.1230
70,ORD0071,08-05-2025,14-05-2025,Customer_002,Female,Pune,Home,Cushion,Upi,3,4561.31,0.05,4.700,13683.93,684.1965,12999.7335
71,ORD0072,10-05-2025,17-05-2025,Customer_049,Female,Delhi,Home,Water Bottle,Upi,4,1560.00,0.05,4.500,6240.00,312.0000,5928.0000
73,ORD0074,13-05-2025,16-05-2025,Customer_032,Female,Delhi,Home,Cushion,Cash,2,3518.45,0.10,3.300,7036.90,703.6900,6333.2100
77,ORD0078,21-05-2025,26-05-2025,Customer_012,Female,Pune,Books,Novel,Cash,5,3867.70,0.00,3.900,19338.50,0.0000,19338.5000
81,ORD0082,28-05-2025,01-06-2025,Customer_033,Female,Coimbatore,Books,Novel,Cash,4,1802.33,0.10,4.600,7209.32,720.9320,6488.3880
83,ORD0084,31-05-2025,05-06-2025,Customer_051,Male,Mumbai,Books,Novel,Credit Card,4,2940.28,0.10,4.600,11761.12,1176.1120,10585.0080
84,ORD0085,02-06-2025,06-06-2025,Customer_043,Male,Bengaluru,Clothing,T-Shirt,Cash,4,1773.66,0.10,2.800,7094.64,709.4640,6385.1760
85,ORD0086,04-06-2025,09-06-2025,Customer_037,Male,Hyderabad,Clothing,T-Shirt,Credit Card,5,2732.59,0.20,3.500,13662.95,2732.5900,10930.3600
87,ORD0088,08-06-2025,09-06-2025,Customer_003,Male,Madurai,Electronics,Headphones,Upi,4,2965.35,0.05,2.900,11861.40,593.0700,11268.3300
88,ORD0089,10-06-2025,17-06-2025,Customer_001,Male,Chennai,Books,Novel,Debit Card,4,2061.47,0.15,3.100,8245.88,1236.8820,7008.9980
89,ORD0090,11-06-2025,16-06-2025,Customer_033,Female,Delhi,Home,Table Lamp,Cash,2,3518.57,0.15,4.300,7037.14,1055.5710,5981.5690
91,ORD0092,15-06-2025,17-06-2025,Customer_010,Male,Hyderabad,Books,Novel,Credit Card,4,3512.86,0.15,4.100,14051.44,2107.7160,11943.7240
93,ORD0094,19-06-2025,26-06-2025,Customer_044,Female,Bengaluru,Home,Storage Box,Credit Card,4,4384.16,0.10,3.900,17536.64,1753.6640,15782.9760
94,ORD0095,20-06-2025,26-06-2025,Customer_029,Female,Bengaluru,Home,Storage Box,Upi,4,2624.66,0.00,3.100,10498.64,0.0000,10498.6400
95,ORD0096,22-06-2025,29-06-2025,Customer_013,Male,Coimbatore,Home,Table Lamp,Upi,5,4868.24,0.05,3.400,24341.20,1217.0600,23124.1400
98,ORD0099,28-06-2025,01-07-2025,Customer_046,Female,Madurai,Home,Water Bottle,Upi,3,4126.77,0.10,4.000,12380.31,1238.0310,11142.2790

In [29]:
display(df[df['City'] == 'Chennai'])

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Gender,City,Category,Product,Payment_Mode,Quantity,Unit_Price,Discount,Rating,Total_Price,Discount_Amount,Final_Amount
3,ORD0004,06-01-2025,09-01-2025,Customer_034,Female,Chennai,Clothing,Sneakers,Debit Card,2,1427.69,0.00,3.6,2855.38,0.000,2855.380
28,ORD0029,20-02-2025,24-02-2025,Customer_028,Male,Chennai,Books,Exam Guide,Credit Card,4,3489.40,0.15,4.6,13957.60,2093.640,11863.960
43,ORD0044,20-03-2025,21-03-2025,Customer_036,Female,Chennai,Books,Exam Guide,Debit Card,2,329.79,0.20,4.5,659.58,131.916,527.664
46,ORD0047,25-03-2025,01-04-2025,Customer_037,Female,Chennai,Books,Novel,Upi,5,2541.01,0.00,3.4,12705.05,0.000,12705.050
47,ORD0048,27-03-2025,28-03-2025,Customer_023,Male,Chennai,Clothing,Jacket,Cash,1,2433.43,0.00,4.7,2433.43,0.000,2433.430
48,ORD0049,29-03-2025,01-04-2025,Customer_058,Female,Chennai,Home,Water Bottle,Credit Card,1,4173.72,0.05,3.5,4173.72,208.686,3965.034
51,ORD0052,03-04-2025,04-04-2025,Customer_005,Female,Chennai,Home,Storage Box,Upi,4,4843.07,0.00,3.4,19372.28,0.000,19372.280
54,ORD0055,09-04-2025,13-04-2025,Customer_052,Male,Chennai,Clothing,T-Shirt,Cash,1,2990.78,0.00,4.4,2990.78,0.000,2990.780
60,ORD0061,20-04-2025,21-04-2025,Customer_032,Male,Chennai,Clothing,Jacket,Upi,5,4525.44,0.05,4.8,22627.20,1131.360,21495.840
63,ORD0064,25-04-2025,30-04-2025,Customer_005,Male,Chennai,Electronics,USB Cable,Credit Card,5,3079.63,0.00,4.8,15398.15,0.000,15398.150
74,ORD0075,15-05-2025,17-05-2025,Customer_027,Male,Chennai,Electronics,USB Cable,Cash,1,4002.71,0.20,3.1,4002.71,800.542,3202.168
76,ORD0077,19-05-2025,24-05-2025,Customer_024,Male,Chennai,Books,Novel,Upi,1,4226.25,0.00,2.6,4226.25,0.000,4226.250
78,ORD0079,22-05-2025,25-05-2025,Customer_050,Male,Chennai,Clothing,T-Shirt,Upi,3,424.56,0.20,4.4,1273.68,254.736,1018.944
86,ORD0087,06-06-2025,13-06-2025,Customer_012,Female,Chennai,Home,Table Lamp,Debit Card,2,2354.58,0.15,4.5,4709.16,706.374,4002.786
88,ORD0089,10-06-2025,17-06-2025,Customer_001,Male,Chennai,Books,Novel,Debit Card,4,2061.47,0.15,3.1,8245.88,1236.882,7008.998
90,ORD0091,13-06-2025,18-06-2025,Customer_040,Male,Chennai,Books,Novel,Credit Card,2,982.33,0.10,4.3,1964.66,196.466,1768.194
92,ORD0093,17-06-2025,19-06-2025,Customer_043,Male,Chennai,Home,Water Bottle,Upi,2,2117.14,0.00,4.2,4234.28,0.000,4234.280

In [31]:
df_sorted = df.sort_values(by='Final_Amount', ascending=False)

In [32]:
display(df_sorted.head(5))

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Gender,City,Category,Product,Payment_Mode,Quantity,Unit_Price,Discount,Rating,Total_Price,Discount_Amount,Final_Amount
62,ORD0063,23-04-2025,27-04-2025,Customer_056,Male,Madurai,Electronics,USB Cable,Upi,5,4904.27,0.05,2.8,24521.35,1226.0675,23295.2825
95,ORD0096,22-06-2025,29-06-2025,Customer_013,Male,Coimbatore,Home,Table Lamp,Upi,5,4868.24,0.05,3.4,24341.20,1217.0600,23124.1400
60,ORD0061,20-04-2025,21-04-2025,Customer_032,Male,Chennai,Clothing,Jacket,Upi,5,4525.44,0.05,4.8,22627.20,1131.3600,21495.8400
50,ORD0051,01-04-2025,07-04-2025,Customer_054,Female,Pune,Clothing,Jacket,Cash,5,4100.29,0.00,3.6,20501.45,0.0000,20501.4500
51,ORD0052,03-04-2025,04-04-2025,Customer_005,Female,Chennai,Home,Storage Box,Upi,4,4843.07,0.00,3.4,19372.28,0.0000,19372.2800

In [33]:
print("Top 5 orders with selected columns:")

display(
    df_sorted[
        ['Order_ID',
         'Product',
         'Category',
         'Quantity',
         'Final_Amount']
    ].head(5)
)

Top 5 orders with selected columns:

   Order_ID      Product     Category  Quantity  Final_Amount
62  ORD0063    USB Cable  Electronics         5    23295.2825
95  ORD0096   Table Lamp         Home         5    23124.1400
60  ORD0061       Jacket     Clothing         5    21495.8400
50  ORD0051       Jacket     Clothing         5    20501.4500
51  ORD0052  Storage Box         Home         4    19372.2800